#!/usr/bin/env bash

# required if starting this script via MAC gui (double-clicked scripts 
# start in HOME in OS X rather than PWD by default.
cd -- "$(dirname "$0")"

hosts=(\
	"10.0.0.10" \
	"10.0.0.20" \
	"10.0.0.30" \
	"10.0.0.40" \
	"10.0.0.50" \
)

for i in "${hosts[@]}"
do
	echo "Shutting down $i"
	ssh -o ConnectTimeout=5 -tt -t pi@$i "sudo halt -p"
done
