#!/bin/bash
#Montana State University NeuroCAVE
#Headset Pairing Utility


echo "Automatic Pairing Utility"

function conn {
	address=$(echo $1 | tr -d '"')
	echo "Attempting connection to $address"
	echo raspberry | sudo -kS ./bin/gort bluetooth connect "${address}" /dev/rfcomm0
	echo raspberry | sudo -kS ./bin/gort bluetooth serial "${address}" /dev/rfcomm0
}

target_address=$1
echo "Target MAC address: $target_address"

while :
do
    conn $target_address
    sleep 3
done
