#!/bin/bash
#Montana State University NeuroCAVE
#Headset Pairing Utility


echo "Automatic Pairing Utility"

address=$1
echo "Target MAC address: $address"

bluetoothctl <<EOF
	scan on
EOF
rfcomm connect "hs1" $address &
sleep 10
bluetoothctl -a <<EOF
	trust $address
	scan off
EOF
