{
    # Incoming and outgoing network settings
    "listen_ip": "127.0.0.1",
    "listen_port": 7770,
    "controller_ip": "10.7.153.129",      # IP of the Artnet controller
    "lighting_configuration": "./config/rigs/pod-rig.yaml",
    "min_intensity": 255,
    "max_intensity": 255,
    "start_color": {
      "red": 255,
      "green": 0,
      "blue": 0,
    },
    "end_color": {
      "red": 0,
      "green": 255,
      "blue": 255,
    },
    "headsetoff_color": {
      "red": 255,
      "green": 255,
      "blue": 255,
      "intensity": 45,
    },
    "pulse_amount": 3.0,
    "pulse_length": 4,
    "pulse_pause": 4,
    "color_granularity": 10,  # number of messages to generate for a transition

    # switch between headset on/off - true: headset on
    # for demo, set default_on to False to make the pod pulse
    # set default_on to True to make the pod use incoming eeg messages
    "default_on": True,

    # 0 - timestamp
    # 1 - delta
    # 2 - high alpha
    # 3 - high beta
    # 4 - lo alpha
    # 5 - lo beta
    # 6 - lo gamma
    # 7 - mid gamma
    # 8 - theta
    "channel_id": 4,          # EEG channel to listen to
    "scaler": 17000000,       # number to scale EEG values by
}